name: Build

on:
  push:
    branches: ["master"]
    tags:
      - "v*"
  pull_request:
    branches: ["master"]

env:
  OSEXT_MAP: '{"Linux": "linux", "macOS": "macos", "Windows": "exe"}'
  CACHE_PREFIX: upload-${{ github.run_id }}-${{ github.run_attempt }}

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  build:
    name: Test with ${{ matrix.go-version }} on ${{ matrix.vm-os }}
    runs-on: ${{ matrix.vm-os }}
    permissions:
      contents: write
    env:
      # CI_REPORT: ${{ matrix.vm-os == 'ubuntu-20.04' && matrix.go-version == '1.18.10' }}
      CI_REPORT: false
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        vm-os: [
          ubuntu-20.04,
          # macos-13,
          macos-14,
          windows-2022
        ]
        go-version: [
          1.18.10,
          # 1.19.13,
          # 1.20.14,
          # 1.21.10,
          # 1.22.3,
        ]
    # Steps to execute
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Go Build
        run: |
          export
          git status
          go version
          go mod download
          make --version
          make build
      - name: Test
        env:
          OSEXT: ${{ fromJSON(env.OSEXT_MAP)[runner.os] }}
        run: |
          make preview
          make artifact

      - name: Get current date
        id: get_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Upload Artifact for Development
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: distbed-dev
          path: _upload

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Built on ${{ steps.get_date.outputs.date }}"
          files: |
            _upload/*

      - name: Analyze on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          # Setup
          wget -cqL https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-i686-unknown-linux-musl.tar.gz -O tokei.tgz
          tar zxf tokei.tgz tokei && chmod +x tokei && $SUDO mv tokei /usr/local/bin && rm tokei.tgz
          wget -cqL https://github.com/mgechev/revive/releases/download/v1.3.7/revive_linux_amd64.tar.gz -O revive.tgz
          tar zxf revive.tgz revive && chmod +x revive && $SUDO mv revive /usr/local/bin && rm revive.tgz
          wget -cqL https://raw.githubusercontent.com/1set/meta/master/revive.toml -O revive.toml
          # Analyze
          echo "# Analysis on Linux" > $GITHUB_STEP_SUMMARY
          uname -a >> $GITHUB_STEP_SUMMARY
          # --- count lines of code
          echo "## Tokei Result" >> $GITHUB_STEP_SUMMARY
          printf '\n```\n' >> $GITHUB_STEP_SUMMARY
          tokei >> $GITHUB_STEP_SUMMARY
          printf '```\n\n' >> $GITHUB_STEP_SUMMARY
          # --- lint
          echo "## Revive Result" >> $GITHUB_STEP_SUMMARY
          printf '\n```\n' >> $GITHUB_STEP_SUMMARY
          revive -config revive.toml -formatter friendly ./... >> $GITHUB_STEP_SUMMARY
          printf '```\n\n' >> $GITHUB_STEP_SUMMARY
          # --- file size
          echo "## File Size" >> $GITHUB_STEP_SUMMARY
          printf '\n```bash\n' >> $GITHUB_STEP_SUMMARY
          ls -laSh >> $GITHUB_STEP_SUMMARY
          printf '```\n\n```bash\n' >> $GITHUB_STEP_SUMMARY
          find . -maxdepth 1 -type f -size +524288c | xargs -I {} stat --format="%n %s" {} | awk '{printf "%s\t\t%sB\n", $1, $2}' >> $GITHUB_STEP_SUMMARY
          printf '```\n\n' >> $GITHUB_STEP_SUMMARY

      - name: Analyze on macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          # Setup
          wget -cqL https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-x86_64-apple-darwin.tar.gz -O tokei.tgz
          tar zxf tokei.tgz tokei && chmod +x tokei && $SUDO mv tokei /usr/local/bin && rm tokei.tgz
          wget -cqL https://github.com/mgechev/revive/releases/download/v1.3.7/revive_darwin_amd64.tar.gz -O revive.tgz
          tar zxf revive.tgz revive && chmod +x revive && $SUDO mv revive /usr/local/bin && rm revive.tgz
          wget -cqL https://raw.githubusercontent.com/1set/meta/master/revive.toml -O revive.toml
          # Analyze
          echo "# Analysis on macOS" > $GITHUB_STEP_SUMMARY
          uname -a >> $GITHUB_STEP_SUMMARY
          # --- count lines of code
          echo "## Tokei Result" >> $GITHUB_STEP_SUMMARY
          printf '\n```\n' >> $GITHUB_STEP_SUMMARY
          tokei >> $GITHUB_STEP_SUMMARY
          printf '```\n\n' >> $GITHUB_STEP_SUMMARY
          # --- lint
          echo "## Revive Result" >> $GITHUB_STEP_SUMMARY
          printf '\n```\n' >> $GITHUB_STEP_SUMMARY
          revive -config revive.toml -formatter friendly ./... >> $GITHUB_STEP_SUMMARY
          printf '```\n\n' >> $GITHUB_STEP_SUMMARY
          # --- file size
          echo "## File Size" >> $GITHUB_STEP_SUMMARY
          printf '\n```bash\n' >> $GITHUB_STEP_SUMMARY
          ls -laSh >> $GITHUB_STEP_SUMMARY
          printf '```\n\n```bash\n' >> $GITHUB_STEP_SUMMARY
          find . -maxdepth 1 -type f -size +524288c | xargs -I {} stat -f "%N %z" {} | awk '{printf "%s\t\t%sB\n", $1, $2}' >> $GITHUB_STEP_SUMMARY
          printf '```\n\n' >> $GITHUB_STEP_SUMMARY
